#kind: Secret
#apiVersion: v1
#metadata:
#  name: ocb-dockerconfigjson-github-com
#data:
#  .dockerconfigjson: >-
#    eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJhbWxuYm1WemFDNW5ZVzVuWVc1cFFHWnBiMjVsWlhJdVkyOXRPbWRvY0Y5dE9WaHBhSGhpTms5TlozSkpUa3hHTkRCQ1IxTlljVkZCVERORFVYa3phSEZsUlc4PSJ9fX0=
#type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: Secret
metadata:
  name: ocb-grafana-secret
type: Opaque
data:
  # username admin
  admin-user: YWRtaW4=
  admin-password: UGFzczEyMzQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: ocb-hana-secret
type: Opaque
data:
  # echo -n '<PWD>' | base64
  hana-username: T0NCQURN
  hana-password: U2Fwb2NiMjAyMyY=
